### PR TITLE
Cdap ui/widget plugin

### PR DESCRIPTION
**Pull request by neelesh-nirmal**
CDAP provides many widget uis for plugin representation listed here [CDAP plugin representation](https://docs.cask.co/cdap/4.2.0/en/developer-manual/pipelines/developing-plugins/presentation-plugins.html)

Simler to above listed widgets this PR contains two more ui widgets that we can use in  any cdap plugin configuration.

### Filter Content Widget
This ui widget alters(show/hide) the ui configuration of a plugin based on some selected values of a plugin property.

### Multi Key Value Widget
CDAP also provides support for multiple key value type widget but it has some limitation like
- At a time you can either choose key or value from input schema or from predefined configuration.
- No support for user input as key or value.

So this widget solves above issue. Using this widget, for any key or value user can use any combination like:
- Choose values from input schema
- Choose values from predefined schema
- Or let the user enter is manually at the time of pipeline creation.

Basic configuration of the widgets are available below:
- [Content Filter Widget](https://guavus.atlassian.net/wiki/spaces/RAF/pages/249823233/Content+Filter+Widget)
- [Multi Key Value Widget](https://guavus.atlassian.net/wiki/spaces/RAF/pages/248545346/CSV+Widget)

### CODE REVIEW

**Comment by neelesh-nirmal** [comment]
[RP-2090](https://guavus-jira.atlassian.net/browse/RP-2090)
[RP-1739](https://guavus-jira.atlassian.net/browse/RP-1739)
[RP-1813](https://guavus-jira.atlassian.net/browse/RP-1813)

**Comment by miraj-godha-guavus** [comment]
Please send merger request to latest branch.

**Comment by neelesh-nirmal** [comment]
@miraj-godha-guavus Please let m know which branch ??

**Review by anujkanojia — APPROVED** [review]
Code reviewed and checked few scenarios

**Pull request merged**
