### PR TITLE
Fix/add ldap user search filter

### PR DESCRIPTION
**Pull request by ankur-gupta-guavus**
Added a new configurable parameter to provide ldap userSearchFilter. Also updated jetty-plus custom jar version in pom.xml. That jar has been pushed to Guavus artifactory.

### CODE REVIEW

**Comment by miraj-godha-guavus** [comment]
jetty plus version needs to be changed in base cdap jar as not sure how that jar is referred internally, when CDAP is dployed

CDAP main POM
<dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-plus</artifactId>
        <version>${jetty8.version}</version>
      </dependency>
      <dependency>

**Comment by ankur-gupta-guavus** [comment]
Updated

**Comment by miraj-godha-guavus** [comment]
Speical change in jetty jar, new jetty plus jar created locally for user role bug at Jio.

8.1.15.v20190208

**Comment by miraj-godha-guavus** [comment]
https://issues.cask.co/browse/CDAP-13199

**Comment by miraj-godha-guavus** [comment]
https://issues.cask.co/browse/CDAP-13199

**Pull request merged**
